spring:
    #        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    security:

# ===================================================================
# Logging level configuration
# ===================================================================
logging:
    level:
        root: INFO
        org:
            hibernate:
                SQL: INFO
            springframework:
                security: INFO
            fernando:
                gg: INFO